replicaCount: 1
namespace: auth

image: 
  repository: "<ecr_auth_repository_link>"
  tag: "dev-latest"
  pullPolicy: IfNotPresent

service: 
  type: ClusterIP
  port: 80
  targetPort: 3000

configMap:
  enabled: true

  data: 
    NODE_ENV: development
    PORT: "3000"

externalSecret:
  enabled: true
  remoteSecretName: "vauras-luxury-app/dev/app-secrets"

autoscaling: 
  enabled: false 

resources:
  requests:
    cpu: 100m 
    memory: 128Mi

  limits:
    cpu: 500m 
    memory: 512Mi    

readinessProbe:
  httpGet:
    path: /api/auth/health    


livenessProbe:
  httpGet:
    path: /api/auth/health   