replicaCount: 3
namespace: auth

image: 
  repository: "<ecr_auth_repo>"
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

configMap:
  enabled: true

  data: 
    NODE_ENV: production
    PORT: "3000"


secret: 
  enabled: true
  data:
    JWT_SECRET: ""  
    DB_HOST: ""
    DB_PORT: ""
    DB_NAME: ""
    DB_USER: ""
    DB_PASSWORD: ""

autoscaling:
  enabled: true

  minReplicas: 3
  maxReplicas: 10

  targetCPUUtilizationPercentage: 70

resources:
  requests:
    cpu: 200m
    memory: 256Mi

  limits:
    cpu: "1"
    memory: 512Mi                

readinessProbe:
  httpGet:
    path: /api/auth/health        

livenessProbe:
  httpGet:
    path: /api/auth/health       