replicaCount: 1

namespace: cart 

image:
  repository: "<ecr_cart_repository>"
  tag: "dev-latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 3001

configMap:
  enabled: true

  data:
    NODE_ENV: development
    PORT: "3001"

externalSecret:
  enabled: true
  remoteSecretName: "vauras-luxury-app/dev/app-secrets"

  
autoscaling:
  enabled: false 

resources: 
  requests:
    cpu: 100m 
    memory: 128Mi
  
  limits:
    cpu: 500m 
    memory: 512Mi

readinessProbe:
  httpGet:
    path: /api/cart/health        

livenessProbe:
  httpGet:
    path: /api/cart/health   
