name: Reusable Workflow 

on:
  workflow_call:
    
    outputs:
      environment:
        description: "Deployment environment (dev/prod)"
        value: ${{ jobs.environment.outputs.environment }}
      
      aws-region:
        description: "AWS Region"
        value: ${{ jobs.global.outputs.aws-region }}
      
      aws-role:
        description: "IAM Role ARN"
        value: ${{ jobs.global.outputs.aws-role }}
        
      cluster-name:
        description: "EKS Cluster Name"  
        value: ${{ jobs.global.outputs.cluster-name }}
        
      changed-files:
        description: "Changed files"
        value: ${{ jobs.changes.outputs.changed-files }}
        

jobs:
  
  environment:

    name: Determine Environment
    
    runs-on: ubuntu-latest

    outputs:
      environment: ${{ steps.detect.outputs.environment }}
    
    steps:
      
      - name: Detect Environment

        id: detect

        shell: bash

        run: |
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            echo "environment=prod" >> "$GITHUB_OUTPUT"
          else
            echo "environment=dev" >> "$GITHUB_OUTPUT"
          fi    

  global:
    
    name: Determine Global Outputs

    runs-on: ubuntu-latest
    
    needs: environment

    outputs:
      aws-region: ${{ steps.global.aws-region }}
      aws-role: ${{ steps.global.outputs.aws-role }}
      cluster-name: ${{ steps.global.outputs.cluster-name }}

    steps:
      
      - name: Set Global Outputs
        
        id: global

        shell: bash

        run: |
          if [[ "${{ needs.environment.outputs.environment }}" == "dev" ]]; then
            echo "aws-region=ap-south-1" >> "$GITHUB_OUTPUT"
            echo "aws-role=DEV_ROLE_PLACEHOLDER" >> "$GITHUB_OUTPUT"
            echo "cluster-name=dev-cluster" >> "$GITHUB_OUTPUT"
           
          else
            
            echo "aws-region=ap-south-1" >> "$GITHUB_OUTPUT"
            echo "aws-role=PROD_ROLE_PLACEHOLDER" >> "$GITHUB_OUTPUT"
            echo "cluster-name=prod-cluster" >> "$GITHUB_OUTPUT"
          
          fi
          
  changes:
    
    name: Detect Changed Files

    runs-on: ubuntu-latest

    needs: environment

    outputs:
      changed-files: ${{ steps.detect.outputs.changed-files }}
    
    steps:
      - name: Checkout Repository
        
        uses: actions/checkout@v4

        with: 
          fetch-depth: 0
          
      - name: Detect Changed Files
        
        id: detect

        shell: bash

        run: |
          echo "Implementation will come here"